/*
 * This file is generated by jOOQ.
 */
package com.jooq.demo.db.tables.records;


import com.jooq.demo.db.tables.DynamicUser;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DynamicUserRecord extends UpdatableRecordImpl<DynamicUserRecord> implements Record3<Integer, String, Byte> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>test.dynamic_user.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>test.dynamic_user.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>test.dynamic_user.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>test.dynamic_user.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>test.dynamic_user.gender</code>.
     */
    public void setGender(Byte value) {
        set(2, value);
    }

    /**
     * Getter for <code>test.dynamic_user.gender</code>.
     */
    public Byte getGender() {
        return (Byte) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, String, Byte> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Integer, String, Byte> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return DynamicUser.DYNAMIC_USER.ID;
    }

    @Override
    public Field<String> field2() {
        return DynamicUser.DYNAMIC_USER.NAME;
    }

    @Override
    public Field<Byte> field3() {
        return DynamicUser.DYNAMIC_USER.GENDER;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public Byte component3() {
        return getGender();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public Byte value3() {
        return getGender();
    }

    @Override
    public DynamicUserRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public DynamicUserRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public DynamicUserRecord value3(Byte value) {
        setGender(value);
        return this;
    }

    @Override
    public DynamicUserRecord values(Integer value1, String value2, Byte value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DynamicUserRecord
     */
    public DynamicUserRecord() {
        super(DynamicUser.DYNAMIC_USER);
    }

    /**
     * Create a detached, initialised DynamicUserRecord
     */
    public DynamicUserRecord(Integer id, String name, Byte gender) {
        super(DynamicUser.DYNAMIC_USER);

        setId(id);
        setName(name);
        setGender(gender);
    }
}
