/*
 * This file is generated by jOOQ.
 */
package com.jooq.demo.db;


import com.jooq.demo.db.tables.DynamicUser;
import com.jooq.demo.db.tables.records.DynamicUserRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in 
 * test.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<DynamicUserRecord> KEY_DYNAMIC_USER_PRIMARY = Internal.createUniqueKey(DynamicUser.DYNAMIC_USER, DSL.name("KEY_dynamic_user_PRIMARY"), new TableField[] { DynamicUser.DYNAMIC_USER.ID }, true);
}
