/*
 * This file is generated by jOOQ.
 */
package com.jooq.demo.db;


import com.jooq.demo.db.tables.DynamicUser;


/**
 * Convenience access to all tables in test.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>test.dynamic_user</code>.
     */
    public static final DynamicUser DYNAMIC_USER = DynamicUser.DYNAMIC_USER;
}
